version: "3.8"

services:
  mongo:
    build: ./mongo
    restart: always
    ports:
      - 27017:27017
    networks:
      - bank_network
    volumes:
      - ./mongo/data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: guest
      MONGO_INITDB_ROOT_PASSWORD: guest
      MONGO_INITDB_DATABASE: test

  api:
    build: .
    environment:
      MONGO_URI: mongodb://guest:guest@mongo:27017/
    ports:
      - 3000:3000
    depends_on:
      - mongo
    links:
      - mongo
    networks:
      - bank_network
    restart: on-failure

networks:
  bank_network:
    driver: bridge
